youngjun217/CoDream_SSD

.gitignore
[Problem] git Clone 시 원치 않는 file이 change로 인식 됨
[Solution] .gitignore file 을 추가하는 PR 입니다.
=> [Fix] Add .gitignore

shell.py
shell.py에 fullread 함수만 구현하였습니다.
=> [Feature] fullread 함수 구현

shell.py, test_shell.py
shell.py fullread 함수 내부 print 구문에 줄넘김을 삭제하였습니다.
shell.py fullread 함수에 대한 unit test 구현하였습니다.
=> [UnitTest] test_fullread Unit Test 구현

ssd.py, test_ssd.py
[Problem] function name 의 통일성이 없음
[Solution] read/write function name을 통합함
=> [Refactoring] SSD Function name integration

shell.py, test_shell.py
LBA 4번에 랜덤한 값을 적고 0,3,1,5번에 같은 값을 적어서 모두 일치하는지 확인하는 함수 구현. 이를 테스트하기위한 test_PartialLBAWrite() 구현도 완료.
=> [feature:PartialLBAWrite] 30회 반복

.gitignore, shell.py, ssd.py, test_shell.py, test_ssd.py
WriteReadAging함수를 TDD로 구현하였습니다.
=> [feature] add WriteReadAging function in shell.py

shell.py, test_shell.py
- shell.fullread 함수를 ssd.read_ssd 함수 사용하도록 변경
- test_shell.test_fullread 함수를 ssd.read_ssd를 대체할 mock 사용하도록 변경
=> [Refactor] shell.fullread 함수를 ssd.read_ssd 함수 사용하도록 변경

shell.py
=> [feature] Add help function in shell.py

ssd.py, test_ssd.py
[Problem] SSDOutput class 를 사용하고 있지 않음
[Solution] SSDOutput class를 사용하도록 변경
=> [Refactoring] Using SSDOutput Class

test_ssd.py
mock을 이용한 ssd write behavior test를 추가했습니다.
이후에 다른 unittest를 추가하기보다 리팩토링 쪽으로 진행해보고자합니다~!
=> [feat] add ssd write output behavior test

shell.py, test_shell.py
writereadaging 함수를 변경된 클래스들에 맞게 그린단계까지 간단하게 리팩토링하였습니다.
추후에 테스트를 더 추가할 예정입니다.
=> [refactor] refactor writeReadAging

ssd.py
[Problem] ssd.py를 subprocess로 접근하는 방법이 없음
[Solution] ssd.py를 subprocess로 접근할 수 있도록 main 함수 작성
=> [Feature] Enable subprocess ssd.py

shell.py, test_shell.py
WriteReadAging 함수 사용시 index버그가 있어 수정하였습니다.
=> [fix] fix error of index when call WriteReadAging

shell.py, ssd.py, test_shell.py
=> [feature] add erase func in shell.py

ssd.py, test_ssd.py
[Problem] erase_ssd 구현이 필요함
[Solution] erase_ssd 의 run function 초기 구현
=> [Feature] Add ssd erace run unittest

shell.py
=> [Feature] Logger 클래스 및 print 함수 구현

shell.py, test_shell.py
rotate_log_if_needed()를 print()내부에 넣어서 Logger구현 및 싱글톤 적용하였습니다.
=> feature(refactor) Logger 클래스 내부 함수 합치기 및 싱글톤 적용

shell.py
복붙의 폐해..
모든 logger가 read 함수로 남고 있는 부분 수정하였습니다. 😂
=> [Fix] 각 함수별 log가 올바르게 기록되도록 수정

.gitignore, buffer.py
[Buffer 잔여 action item]
1. F 명령어 flush랑 연결
2. Buffer 5개 찼을때 새로운 명령어가 오면 buffer 자동 flush 및 비우기 구현
3. Read 시 buffer 에 해당 주소 Write/Erase 있는지 확인 및 반환
4. 중복 주소 Write/Erase 시 통폐합
5. Execute 기능 (실제 Write/Erase) 구현
중에서 2번과 5번 구현입니다
=> [feat] buffer flush and execute

ssd_driver.py
[Refactor] Adapter Pattern 적용을 위한 Adapter Interface Class 추가
=> [Refactor] Adapter Pattern 적용을 위한 Adapter Interface Class 추가

shell.py
Reverts youngjun217/CoDream_SSD#63
[fix]
-EraseAndWriteAging 함수인 경우 erase log무시하게 로직 변경
-log test
=> Revert "Revert "Feature/yj""

buffer.py
최초 클래스 선언시 버퍼 파일을 생성하고, 
file 이름 read기능 대신 lst 와 creation으로 대체했습니다.
=> [feat] buffer file creation

buffer.py
이전 PR에서 제가 기존에 있던 기능부분을 삭제했어서
다시 추가를 하려다가 lst 를 활용하는 부분으로 수정을 했습니다!
=> [fix] use buffer list for  buffer execution instead of files

ssd_interface.py
=> [Fix] ssd_driver -> ssd_interface로 파일 이름 및 클래스 이름 변경

ssd.py
```_check_buffer```함수를 run시작 후 바로 진행하게 하여 이쪽에서  아래 기능들을 구현하는게 더 깔끔할까요?
- Read 시 buffer 에 해당 주소 Write/Erase 있는지 확인 및 반환
- 중복 주소 Write/Erase 시 통폐합
=> [refactor]  buffer기능을 이렇게 구현하는게 나을까요?

ssd.py
Write커멘드를 받았을 때 Buffer내 명령어와 통합하는 기능을 추가하였습니다.
=> [feature] 새로운 커맨드가 Write일 때 Buffer내 명령과 통합

ssd.py, test_ssd.py
[Problem] Bad code smell
[Solution] SSD command를 상속을 사용함으로써 refactoring 진행
=> [Refactoring] Use Inherit to SSD commands 

shell.py, ssd_interface.py
[Problem] Shell.py 와 ssd.py 의 결합도가 높아 새로운 ssd 가 add 될 경우, 구조적 변경이 필요함
[Solution] SSD Interface를 활용하도록 변경
=> [Refactoring] Using SSD Interface

.gitignore, buffer.py, latest.log, ssd.py, ssd_interface.py
=> [fix] 순환참조를 해결하였습니다.

ssd_interface.py
shell에서 run할 때마다 buffer가 초기화되는 버그를 해결하였습니다.
=> [fix] fix buffer

ssd_texts.py
[Problem] Singleton class 생성시 testfile이 계속 초기화 됨
[Solution] 생성시에만 초기화 하도록 변경
=> [Fix] Wrong initialize for singleton textfile

shell.py
shell.py내에 flushcommand 클라스 추가, 추후 execute 기능개발 필요
=> [feature] shell.py내에 flushcommand 클라스 추가, 추후 execute 기능개발 필요

buffer.py
shell에서 write했을 때 output파일이 변경되도록 버그 수정하였습니다.
=> [fix] bugfix on write buffer

shell.py
외부 클래스에서 함수를 사용해서 naming 변경입니다.
=> [refactor] _get_response()와 _get_response_value() 의 앞에 언더바 제거.

buffer.py
buffer에서 flush기능을 추가하였습니다.
- buffer list에 5개의 명령어가 차면 flush 자동 실행
- shell에 F라는 명령어가 들어오면 flush 실행
=> [feature] buffer flush function

ssd.py, ssd_texts.py
[Problem] test_tdd 에서 Erase 부분이 fail 발생
[Solution] Read nand text 시에 항상 100 lines을 반환하도록 변경
=> [Fix] Erase Test Error Fix

buffer.py
Buffer를 command/value를 관리하는 list 2개로 관리하여 
매번 command 들어올 때마다 buf_lst를 업데이트 하도록 수정했습니다.
buf_lst가 6개 이상됐을때 flush하는 부분 추가가 필요합니다.
=> [feat] Feature/buffer write

shell.py, test_ssd.py
[Problem] Hex Value print 가 다르게 print 됨
[Solution] Hex Value print를 통일함
=> [Refactor] Unify Hex Value print

buffer.py, ssd.py, ssd_commands.py, test_buffer.py, test_ssd.py
[Problem] Buffer dependency 가 SSD 와 서로 중복 
[Solution] Dependency 해결 및 Creation rule 변경, Unit test 추가
=> [Feature] Buffer dependency & add Unittest

ssd.py, ssd_commands.py, ssd_interface.py, ssd_texts.py, test_ssd.py
[Problem] Flush 기능 미구현
[Solution] Flush 기능 구현 및 refactoring
=> [Feature] Add Flush Command

buffer.py, ssd.py, test_buffer.py, test_ssd.py
[Problem] Buffer function 이 disable 되어 있음
[Solution] Buffer refactoring 및 feature enable
=> [Feature] Add Buffer function

test_buffer.py
[Problem] test_buffer.py 가 100% pass 하지 않음
[Solution] 100% pass 하도록 수정
=> [Fix] make test_buffer.py with 100%

buffer.py, ssd.py, ssd_commands.py, ssd_texts.py, test_ssd.py
[Problem] ssd.py의 test coverage가 100% 가 아님
[Solution] ssd.py의 test coverage가 100% 가 되도록 unittest 추가 및 리팩토링
=> [Refactoring] ssd.py test coverage 100%

test_shell.py
[Feature] SSDConcreteInterface의 run(), get_response()까지 정상적으로 call 되는지 확인하는 Unit Test 함수 추가
=> [Feature] SSDConcreteInterface의 run(), get_response()까지 정상적으로 call 되는지 확인하는 Unit Test 함수 추가

test_buffer.py
[Problem] buffer.py의 test coverage가 100% 가 아님
[Solution] buffer.py의 test coverage가 100% 가 되도록 unittest 추가 및 리팩토링
=> [Refactoring] test coverage 100% of buffer.py
